export const menudata = [
  {
    id: 1,
    title: "Buttermilk pancakes",
    category: "breakfast",
    price: `$15.99`,
    img: `${process.env.PUBLIC_URL}/images/item-1.jpeg`,
    alt: "Buttermilk pancakes",
    desc: "普通のパンケーキです。",
  },
  {
    id: 2,
    title: "Diner double",
    category: "lunch",
    price: 13.99,
    img: `${process.env.PUBLIC_URL}/images/item-2.jpeg`,
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    alt: "Diner double",
  },
  {
    id: 3,
    title: "Godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: `${process.env.PUBLIC_URL}/images/item-3.jpeg`,
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    alt: "Godzilla milkshake",
  },
  {
    id: 4,
    title: "Country delight",
    category: "breakfast",
    price: 20.99,
    img: `${process.env.PUBLIC_URL}/images/item-4.jpeg`,
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    alt: "Country delight",
  },
  {
    id: 5,
    title: "Egg attack",
    category: "lunch",
    price: 22.99,
    img: `${process.env.PUBLIC_URL}/images/item-5.jpeg`,
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    alt: "Egg attack",
  },
  {
    id: 6,
    title: "Oreo dream",
    category: "shakes",
    price: 18.99,
    img: `${process.env.PUBLIC_URL}/images/item-6.jpeg`,
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    alt: "Oreo dream",
  },
  {
    id: 7,
    title: "Bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: `${process.env.PUBLIC_URL}/images/item-7.jpeg`,
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    alt: "Bacon overflow",
  },
  {
    id: 8,
    title: "American classic",
    category: "lunch",
    price: 12.99,
    img: `${process.env.PUBLIC_URL}/images/item-8.jpeg`,
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    alt: "American classic",
  },
  {
    id: 9,
    title: "Quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: `${process.env.PUBLIC_URL}/images/item-9.jpeg`,
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    alt: "Quarantine buddy",
  },
  {
    id: 10,
    title: "Bison steak",
    category: "dinner",
    price: 22.99,
    img: `${process.env.PUBLIC_URL}/images/item-10.jpeg`,
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    alt: "Bison steak",
  },
];
